#!/usr/bin/env python3
"""Pack the rendered gate glyphs into an atlas, in the two forms this mod needs.

Outputs
    atlas.png   one sheet, a row per size, gates left to right. The human-facing
                artifact, and what a future texture-drawing path would sample.
    atlas.json  the region of every sprite in that sheet.
    GateSprites.g.cs  the form the mod actually draws from: run-length rows,
                base64 in one string.

Why runs and not the PNG, given the PNG exists.

    Pixel Art can only put a texture on screen through Canvas.DrawIcon, and that
    has two properties that rule it out here. It loads by res:// path, so the
    sheet would have to ship as a Godot resource pack; and it fits the art into
    78% of the destination rect at a whole-number scale, so a sprite drawn at
    its own size never appears at all -- floor(0.78) is 0. Runs go through
    DrawFill, which the gates already use, needs no resource pack, and keeps the
    existing per-zoom bake.

    The sheet is still worth generating. It is how a person checks the art, and
    it is what a DrawSprite API would want the day one exists.

Canonical facing only: output to the RIGHT. The four rotations are quarter turns
of a square grid, which the mod does at bake time for the cost of a transpose --
holding them here would quadruple the sheet to save nothing.
"""
import base64, json, sys
from PIL import Image

GATES = ('and', 'or', 'xor', 'not')
SIZES = (16, 24, 32, 40, 48, 64, 80, 96)


def border(S):
    """How much to trim from each side, so a glyph does not touch the next cell.

    A sixteenth of the sprite, floored, and never less than one pixel. Floored
    rather than rounded because a sixteenth is not whole at 24 or 40, and the
    alternatives there are worse: seven eighths of those is 21 and 35, both ODD,
    and an odd sprite has no centre line for the output wire to straddle. That
    straddle is the thing the even sizes exist for. Flooring keeps every cropped
    sprite even and still leaves a clear pixel at the smallest size.
    """
    return max(1, S // 16)


def ink(path, b):
    """The glyph with `b` pixels trimmed from every side.

    What that removes is the far end of each input leg and of the output stub --
    the parts that ran to the very edge. They still reach the corner and the edge
    of the CROPPED sprite, because they are diagonals from the corner and a run
    to the edge; the glyph simply ends `b` short of the cell it is drawn in. The
    body is untouched.
    """
    im = Image.open(path).convert('L')
    w, h = im.size
    if b:
        im = im.crop((b, b, w - b, h - b))
        w, h = im.size
    px = im.load()
    return w, h, [[px[x, y] < 128 for x in range(w)] for y in range(h)], im


def runs_of(grid, w, h):
    out = []
    for y in range(h):
        x = 0
        while x < w:
            if grid[y][x]:
                s = x
                while x < w and grid[y][x]:
                    x += 1
                out.append((y, s, x - s))
            else:
                x += 1
    return out


def main():
    cropped = {S: S - 2 * border(S) for S in SIZES}
    sheet_w = max(len(GATES) * cropped[S] for S in SIZES)
    sheet_h = sum(cropped.values())
    sheet = Image.new('L', (sheet_w, sheet_h), 255)
    regions = {}
    blob = bytearray()

    y0 = 0
    for S in SIZES:
        for i, g in enumerate(GATES):
            C = cropped[S]
            w, h, grid, im = ink(f'png/{S}_{g}.png', border(S))
            assert (w, h) == (C, C), f'{S}_{g} cropped to {w}x{h}, expected {C}x{C}'
            sheet.paste(im, (i * C, y0))
            regions[f'{g}_{S}'] = dict(x=i * C, y=y0, w=C, h=C, cell=S, border=border(S))

            r = runs_of(grid, w, h)
            # The size recorded is the CELL the sprite is for, not the sprite's own side; the
            # mod looks it up by the zoom rung it is drawing.
            blob += bytes([GATES.index(g), S, len(r) & 0xFF, (len(r) >> 8) & 0xFF])
            for (ry, rx, rl) in r:
                blob += bytes([ry, rx, rl])
        y0 += cropped[S]

    sheet.save('atlas.png')
    json.dump(dict(sheet='atlas.png', size=[sheet_w, sheet_h],
                   gates=list(GATES), sizes=list(SIZES), regions=regions),
              open('atlas.json', 'w'), indent=2, sort_keys=True)

    b64 = base64.b64encode(bytes(blob)).decode()
    wrapped = '\n'.join('        "%s" +' % b64[i:i + 100] for i in range(0, len(b64), 100))
    wrapped = wrapped.rstrip(' +')
    src = '''// GENERATED by art/gates/pack_atlas.py -- do not edit.
//
// The logic-gate glyphs, one bitmap per gate per zoom rung, run-length encoded.
//
// Rendered from art/gates/*.svg by render_gates.py, which snaps every stroke to
// whole pixels at each size rather than scaling one drawing. That is the whole
// point of having eight of them: a 16-pixel glyph is not a shrunken 96-pixel one.
//
// Layout of the blob: per sprite, [gate, size, countLo, countHi] then `count`
// runs of [y, x, length]. Canonical facing is output RIGHT; the four rotations
// are quarter turns applied when the sprite is baked.

namespace PixelInspector;

internal static class GateSprites
{
    /// <summary>The sizes a glyph was drawn at, which are exactly the zoom ladder's rungs.</summary>
    internal static readonly int[] Sizes = { %s };

    /// <summary>The side of the sprite drawn for each cell size, after its border is trimmed.</summary>
    internal static readonly int[] Sides = { %s };

    /// <summary>Gate order within the blob.</summary>
    internal static readonly string[] Names = { %s };

    internal const string Packed =
%s;
}
''' % (', '.join(str(s) for s in SIZES),
       ', '.join(str(cropped[s]) for s in SIZES),
       ', '.join('"%s"' % g for g in GATES),
       wrapped)
    open('GateSprites.g.cs', 'w').write(src)

    print(f'atlas.png  {sheet_w}x{sheet_h}')
    print(f'atlas.json {len(regions)} regions')
    print(f'GateSprites.g.cs  {len(blob)} bytes of runs -> {len(b64)} base64 chars')


if __name__ == '__main__':
    main()
